// 검색을 -> 현규 -> ["1", "2" ...];

const MockData = {
    "1" : [
        {
            "현규" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 50000,
                playerTank : 20000,
                playerHeal : 10000,
            },
            "인태" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 30000,
                playerTank : 70000,
                playerHeal : 20000,
            },
            "민수" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 110000,
                playerHeal : 0,
            },
            "민규" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 10000,
                playerTank : 20000,
                playerHeal : 220000,
            },
            "형래" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 100000,
                playerHeal : 100000,
            },
        }
    ],
    "2" : [
        {
            "동균" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 50000,
                playerTank : 20000,
                playerHeal : 10000,
            },
            "영덕" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 30000,
                playerTank : 70000,
                playerHeal : 20000,
            },
            "태우" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 110000,
                playerHeal : 0,
            },
            "지웅" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 10000,
                playerTank : 20000,
                playerHeal : 220000,
            },
            "민영" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 100000,
                playerHeal : 100000,
            },
        }
    ],
    "3" : [
        {
            "현규" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 50000,
                playerTank : 20000,
                playerHeal : 10000,
            },
            "진규" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 30000,
                playerTank : 70000,
                playerHeal : 20000,
            },
            "찬규" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 110000,
                playerHeal : 0,
            },
            "점숙" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 10000,
                playerTank : 20000,
                playerHeal : 220000,
            },
            "노익" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 100000,
                playerHeal : 100000,
            },
        }
    ],
    "4" : [
        {
            "현규" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 50000,
                playerTank : 20000,
                playerHeal : 10000,
            },
            "인태" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 30000,
                playerTank : 70000,
                playerHeal : 20000,
            },
            "민수" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 110000,
                playerHeal : 0,
            },
            "민규" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 10000,
                playerTank : 20000,
                playerHeal : 220000,
            },
            "형래" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 100000,
                playerHeal : 100000,
            },
        }
    ],
    "5" : [
        {
            "현규" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 50000,
                playerTank : 20000,
                playerHeal : 10000,
            },
            "인태" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 30000,
                playerTank : 70000,
                playerHeal : 20000,
            },
            "민수" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 110000,
                playerHeal : 0,
            },
            "민규" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 10000,
                playerTank : 20000,
                playerHeal : 220000,
            },
            "형래" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 100000,
                playerHeal : 100000,
            },
        }
    ],
    "6" : [
        {
            "현규" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 50000,
                playerTank : 20000,
                playerHeal : 10000,
            },
            "인태" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 30000,
                playerTank : 70000,
                playerHeal : 20000,
            },
            "민수" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 110000,
                playerHeal : 0,
            },
            "민규" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 10000,
                playerTank : 20000,
                playerHeal : 220000,
            },
            "형래" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 100000,
                playerHeal : 100000,
            },
        }
    ],
}

// css, 챔프, 챔프이미지
export default MockData