// 검색을 -> 현규 -> ["1", "2" ...];

const MockData = {
  1: [
    {
      똥개인척하는범: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Lillia',
        playerDeal: 57292,
        playerTank: 21928,
        playerHeal: 11092,
      },
      응뷔페: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Hecarim',
        playerDeal: 30119,
        playerTank: 70190,
        playerHeal: 20181,
      },
      비니빠수르: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Kalista',
        playerDeal: 20112,
        playerTank: 11178,
        playerHeal: 69,
      },
      빅민규: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Kayn',
        playerDeal: 30120,
        playerTank: 20117,
        playerHeal: 10117,
      },
      자조용해: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Briar',
        playerDeal: 20172,
        playerTank: 51821,
        playerHeal: 24820,
      },
    },
  ],

  2: [
    {
      똥개인척하는범: {
        matchFinalResult: 'lose',
        playerTeam: 'A',
        playerChamp: 'Kogmaw',
        playerDeal: 61821,
        playerTank: 41921,
        playerHeal: 6109,
      },
      윤창헌: {
        matchFinalResult: 'lose',
        playerTeam: 'A',
        playerChamp: 'Ahri',
        playerDeal: 40171,
        playerTank: 75171,
        playerHeal: 22171,
      },
      돼두치: {
        matchFinalResult: 'lose',
        playerTeam: 'A',
        playerChamp: 'Annie',
        playerDeal: 27012,
        playerTank: 115120,
        playerHeal: 2002,
      },
      장종훈: {
        matchFinalResult: 'lose',
        playerTeam: 'A',
        playerChamp: 'Darius',
        playerDeal: 10607,
        playerTank: 22007,
        playerHeal: 229070,
      },
      빠삐코: {
        matchFinalResult: 'lose',
        playerTeam: 'A',
        playerChamp: 'Draven',
        playerDeal: 81270,
        playerTank: 41270,
        playerHeal: 7127,
      },
    },
  ],
  3: [
    {
      똥개인척하는범: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Caitlyn',
        playerDeal: 53102,
        playerTank: 27091,
        playerHeal: 12282,
      },
      Oner: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Blitzcrank',
        playerDeal: 32172,
        playerTank: 32911,
        playerHeal: 2298,
      },
      구지철: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Belveth',
        playerDeal: 27172,
        playerTank: 108182,
        playerHeal: 2098,
      },
      자조용해: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Leblanc',
        playerDeal: 11121,
        playerTank: 8927,
        playerHeal: 2219,
      },
      무너진청년: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'masterYi',
        playerDeal: 28182,
        playerTank: 111782,
        playerHeal: 3902,
      },
    },
  ],
  4: [
    {
      겨드랑이킁카킁카: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Aphelios',
        playerDeal: 55174,
        playerTank: 29174,
        playerHeal: 10174,
      },
      역사를잊은민족: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Azir',
        playerDeal: 32120,
        playerTank: 77120,
        playerHeal: 9012,
      },
      스컹크컹스: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Gnar',
        playerDeal: 50120,
        playerTank: 25120,
        playerHeal: 8012,
      },
      빅민규: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Jax',
        playerDeal: 30128,
        playerTank: 12128,
        playerHeal: 0,
      },
      수소폭탄: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Jhin',
        playerDeal: 47198,
        playerTank: 22198,
        playerHeal: 0,
      },
    },
  ],
  5: [
    {
      똥개인척하는범: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Cassiopeia',
        playerDeal: 55187,
        playerTank: 82187,
        playerHeal: 12187,
      },
      사건의지평선: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Lucian',
        playerDeal: 35012,
        playerTank: 15012,
        playerHeal: 2012,
      },
      비니빠수르: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Karthus',
        playerDeal: 28109,
        playerTank: 115109,
        playerHeal: 6109,
      },
      빅민규: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Anivia',
        playerDeal: 20110,
        playerTank: 70110,
        playerHeal: 5011,
      },
      수소폭탄: {
        matchFinalResult: 'win',
        playerTeam: 'A',
        playerChamp: 'Ekko',
        playerDeal: 22099,
        playerTank: 17099,
        playerHeal: 1999,
      },
    },
  ],
  6: [
    {
      똥개인척하는범: {
        matchFinalResult: 'lose',
        playerTeam: 'A',
        playerChamp: 'Fiora',
        playerDeal: 58109,
        playerTank: 22109,
        playerHeal: 17109,
      },
      둔재: {
        matchFinalResult: 'lose',
        playerTeam: 'A',
        playerChamp: 'Malphite',
        playerDeal: 35109,
        playerTank: 60109,
        playerHeal: 6109,
      },
      비니빠수르: {
        matchFinalResult: 'lose',
        playerTeam: 'A',
        playerChamp: 'missFortune',
        playerDeal: 27192,
        playerTank: 10192,
        playerHeal: 0,
      },
      빅민규: {
        matchFinalResult: 'lose',
        playerTeam: 'A',
        playerChamp: 'Gangplank',
        playerDeal: 18991,
        playerTank: 78991,
        playerHeal: 2991,
      },
      수소폭탄: {
        matchFinalResult: 'lose',
        playerTeam: 'A',
        playerChamp: 'Hwei',
        playerDeal: 26182,
        playerTank: 60182,
        playerHeal: 7182,
      },
    },
  ],
};

// css, 챔프, 챔프이미지
export default MockData;
