// 검색을 -> 현규 -> ["1", "2" ...];

const MockData = {
    "1" : [
        {
            "현규" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 50000,
                playerTank : 20000,
                playerHeal : 10000,
            },
            "인태" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'corki',
                champIcon : 'image',
                playerDeal : 30000,
                playerTank : 70000,
                playerHeal : 20000,
            },
            "민수" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'alistar',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 110000,
                playerHeal : 0,
            },
            "민규" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'soraka',
                champIcon : 'image',
                playerDeal : 10000,
                playerTank : 20000,
                playerHeal : 220000,
            },
            "형래" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'zac',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 100000,
                playerHeal : 100000,
            },
        }
    ],
    "2" : [
        {
            "동균" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'katarina',
                champIcon : 'image',
                playerDeal : 53000,
                playerTank : 27000,
                playerHeal : 12000,
            },
            "영덕" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'thresh',
                champIcon : 'image',
                playerDeal : 32000,
                playerTank : 30000,
                playerHeal : 2000,
            },
            "태우" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'jarvan',
                champIcon : 'image',
                playerDeal : 27000,
                playerTank : 108000,
                playerHeal : 2000,
            },
            "지웅" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'nami',
                champIcon : 'image',
                playerDeal : 11000,
                playerTank : 8000,
                playerHeal : 225000,
            },
            "민영" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'leesin',
                champIcon : 'image',
                playerDeal : 28000,
                playerTank : 110000,
                playerHeal : 3000,
            },
        }
    ],
    "3" : [
        {
            "현규" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'kasadin',
                champIcon : 'image',
                playerDeal : 60000,
                playerTank : 40000,
                playerHeal : 6000,
            },
            "진규" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'atrox',
                champIcon : 'image',
                playerDeal : 40000,
                playerTank : 75000,
                playerHeal : 22000,
            },
            "찬규" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'garen',
                champIcon : 'image',
                playerDeal : 27000,
                playerTank : 115000,
                playerHeal : 2000,
            },
            "점숙" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'galio',
                champIcon : 'image',
                playerDeal : 10600,
                playerTank : 22000,
                playerHeal : 229000,
            },
            "노익" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'gangplank',
                champIcon : 'image',
                playerDeal : 80000,
                playerTank : 40000,
                playerHeal : 7000,
            },
        }
    ],
    "4" : [
        {
            "현규" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'graves',
                champIcon : 'image',
                playerDeal : 55000,
                playerTank : 29000,
                playerHeal : 10000,
            },
            "인태" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'nocturne',
                champIcon : 'image',
                playerDeal : 32000,
                playerTank : 77000,
                playerHeal : 9000,
            },
            "민수" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'nidalee',
                champIcon : 'image',
                playerDeal : 50000,
                playerTank : 25000,
                playerHeal : 8000,
            },
            "민규" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'lux',
                champIcon : 'image',
                playerDeal : 30000,
                playerTank : 12000,
                playerHeal : 0,
            },
            "형래" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'rumble',
                champIcon : 'image',
                playerDeal : 47000,
                playerTank : 22000,
                playerHeal : 0,
            },
        }
    ],
    "5" : [
        {
            "현규" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'renekton',
                champIcon : 'image',
                playerDeal : 55000,
                playerTank : 82000,
                playerHeal : 12000,
            },
            "인태" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'lucian',
                champIcon : 'image',
                playerDeal : 35000,
                playerTank : 15000,
                playerHeal : 2000,
            },
            "민수" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'maokai',
                champIcon : 'image',
                playerDeal : 28000,
                playerTank : 115000,
                playerHeal : 6000,
            },
            "민규" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'vi',
                champIcon : 'image',
                playerDeal : 20000,
                playerTank : 70000,
                playerHeal : 5000,
            },
            "형래" : {
                matchFinalResult : 'win',
                playerTeam : 'A',
                playerChamp : 'vayne',
                champIcon : 'image',
                playerDeal : 22000,
                playerTank : 17000,
                playerHeal : 1900,
            },
        }
    ],
    "6" : [
        {
            "현규" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'vladimir',
                champIcon : 'image',
                playerDeal : 58000,
                playerTank : 22000,
                playerHeal : 17000,
            },
            "인태" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'ryze',
                champIcon : 'image',
                playerDeal : 35000,
                playerTank : 60000,
                playerHeal : 6000,
            },
            "민수" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'shaco',
                champIcon : 'image',
                playerDeal : 27000,
                playerTank : 10000,
                playerHeal : 0,
            },
            "민규" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'shen',
                champIcon : 'image',
                playerDeal : 18000,
                playerTank : 78000,
                playerHeal : 2000,
            },
            "형래" : {
                matchFinalResult : 'lose',
                playerTeam : 'A',
                playerChamp : 'nidalee',
                champIcon : 'image',
                playerDeal : 26000,
                playerTank : 60000,
                playerHeal : 7000,
            },
        }
    ],
}

// css, 챔프, 챔프이미지
export default MockData